dist: bionic

language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.13.x

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make build
  - golangci-lint run