version: '3.7'

services:
  hp-middleware-pass:
    volumes:
      - ./sockets:/tmp
    build:
      context: .
      dockerfile: Dockerfile
    image: softonic/hp-pass-middleware:0.1.0
    entrypoint: ["/pass-middleware"]
    environment:
      IN_SOCKET: "/tmp/hp"